import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("active-spin.csv")
print(df.head())
print(df.columns)
print(df.shape)
print(df[["entity_name", "pitch_hand", "active_spin_fourseam"]].sort_values("active_spin_fourseam", ascending=False).head(10))
print(df["active_spin_fourseam"].mean())
print(df.groupby("pitch_hand")["active_spin_fourseam"].mean())
handedness_avg = df.groupby("pitch_hand")["active_spin_fourseam"].mean()
handedness_avg.plot(kind="bar")
plt.title("Average Four-Seam Active Spin by Pitcher Hand")
plt.xlabel("Pitcher Hand")
plt.ylabel("Active Spin %")
plt.show()
df["active_spin_fourseam"].plot(kind="hist")
plt.show()
below_85 = df[df["active_spin_fourseam"] < 85]
print(below_85[["entity_name", "pitch_hand", "active_spin_fourseam"]])
print(df["active_spin_fourseam"].count())
